AATestComboBoxPairs = {  				-- texts to show on the combo/dropdown boxes and their corresponding settings
  ["SliceAdmiralSounds"] = {
    [1] = {  ["setting"] = "Interface\\AddOns\\SliceAdmiral\\Audio\\PriceIsWrong.mp3",			["text"] = "Price is WRONG",  ["extras"] = {["hasColorSwatch"] = true, ["notCheckable"] = "NIL"}, },
    [2] = {  ["setting"] = "Interface\\AddOns\\SliceAdmiral\\Audio\\Old Trumpet A 01.mp3",		["text"] = "Waaaah",          ["extras"] = {["notCheckable"] = "NIL"}, },
    [3] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\6OP00084.mp3',			["text"] = 'BassDrum' },
    [4] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\tambourine.mp3',			["text"] = 'Tambourine' },
    [5] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\cowtown.mp3',			["text"] = 'Cowbell' },
    [6] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\FXHit15.mp3',			["text"] = 'SliceClick' },
    [7] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\HoleA.mp3',				["text"] = 'BoomBoomClap' },
    [8] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\OldDrums2.mp3',			["text"] = 'Marching Band' },
    [9] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\perc09_HH.mp3',			["text"] = 'High Hat 4' },
   [10] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\RawB.mp3',				["text"] = 'BoomBoomThak' },
   [11] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\Arp31-C2.mp3',			["text"] = 'Arpeggiator C2' },
   [12] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\Arp31-C3.mp3',			["text"] = 'Arpeggiator C3' },
   [13] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\Arp31-C4.mp3',			["text"] = 'Arpeggiator C4' },
   [14] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\ScratchShot.mp3',			["text"] = 'ScratchShot' },
   [15] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\StunningHit.mp3',			["text"] = 'StunningHit' },
   [16] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\DNBLoop4.mp3',			["text"] = 'DNBLoop4' },
   [17] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\DNBLoop2.mp3',			["text"] = 'DNBLoop2' },
   [18] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\Scratch4.mp3',			["text"] = 'Scratch4' },
   [19] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\youspin.mp3',			["text"] = 'You Spin Me' },
   [20] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\whats-the-deal.mp3',		["text"] = "What's the Deal?" },
   [21] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\ClubBeatJ.mp3',			["text"] = 'ClubBeatJ' },
   [22] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\growl.mp3',				["text"] = 'Growl' },
   [23] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\OH-YEAH.mp3',			["text"] = 'OH YEAH' },
   [24] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\shaker.mp3',			["text"] = 'Shaker' },
   [25] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\pop.mp3',				["text"] = 'Pop' },
   [26] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\drumrattle.mp3',			["text"] = 'Drum Rattle' },
   [27] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\pingit.mp3',			["text"] = 'Ping' },
   [28] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\switch-on-off.mp3',			["text"] = 'Switch On/Off' },
   [29] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\perc-short.mp3',			["text"] = 'Eth Perc Short' },
   [30] = {  ["setting"] = 'Interface\\AddOns\\SliceAdmiral\\Audio\\perc-long.mp3',			["text"] = 'Eth Perc Long' },
   [31] = {  ["setting"] = "",										["text"] = "None" },
  },
  ["CustomSounds"] = {	
    [1] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\tamb.mp3",			["text"] = "Tamborine" },
    [2] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\bass.mp3",			["text"] = "Bass Drum" },
    [3] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\bleep.mp3",			["text"] = "Bleep" },
    [4] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\drip.mp3",			["text"] = "Drip" },
    [5] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\guts.mp3",			["text"] = "Splat" },
    [6] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\snare.mp3",			["text"] = "Snare" },
    [7] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\bark.mp3",			["text"] = "Dog Bark" },
    [8] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\snap.mp3",			["text"] = "Snap" },
    [9] = {  ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\squash.mp3",			["text"] = "Squash" },
    [10] = { ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\squeek.mp3", 		["text"] = "Squeek" },
    [11] = { ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\waterSplash.mp3", 		["text"] = "Spash" },
    [12] = { ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\wink.mp3", 			["text"] = "Wink" },
    [13] = { ["setting"] = "interface\\addons\\QuickRogueInfo\\sounds\\zoom.mp3", 			["text"] = "Zoom" },
    [14] = { ["setting"] = "Sound\\Creature\\Misc\\IC_GnomeFemale_Event01.wav", 			["text"] = "Oughta Help" },
  },
  ["CustomBars"] = {
    [1] = { ["setting"] = "Buff",					["text"] = "Buff" },
    [2] = { ["setting"] = "DeBuff",					["text"] = "DeBuff" },
    [3] = { ["setting"] = "Cooldown",				["text"] = "Cooldown" },
  },
}
